### ISSUE TITLE
SIGSEGV crashes 

### ISSUE THREAD

**Issue by royzvibel** [lukeredpath/libPusher#139]
Hi,
We have your SDK integrated into our app, and we are receiving crash reports (from flurry)  resulting in this stack trace (trimmed for connivence).
I observed the  [PTPusherEventDispatcher dispatchEvent:] code and couldn't really figure what could cause this.
But still it would be very helpful to have a try catch around that area. with a log maybe 
I would add it myself but we use Cocoapods, and it makes every code change a headache.

Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0xd000000c
_objc_msgSend + 5
1   [PTPusherEventDispatcher dispatchEvent:] + 214
2   [PTPusherChannel dispatchEvent:] + 70
3   [PTPusher pusherConnection:didReceiveEvent:] + 298
4   [PTPusherConnection webSocket:didReceiveMessage:] + 494
5   [SRWebSocket _handleMessage:]_block_invoke + 55 (SRWebSocket.m:753)

**Comment by hamchapman** [comment]
Closing as stale
