### ISSUE TITLE
Pusher crashing when tried to subscribe to a channel (Works in simulator only)

### ISSUE THREAD

**Issue by sumitsh87** [lukeredpath/libPusher#144]
I am facing the same issue "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PTPusherEventDispatcher addEventListenerForEventNamed:block:queue:]: unrecognized selector sent to instance 0xa6a40b0" when i try to subscribe to a channel.

last week it used to work for simulator and fail for iOS device. But now it fails for both. Please help :(

if it is the compilation problem for the library, Where can i download the latest 1.5 libpusher compiled lib?

**Comment by hamchapman** [comment]
Closing as stale
