### ISSUE TITLE
Assertion failure in -[SRWebSocket send:]

### ISSUE THREAD

**Issue by trilorez** [lukeredpath/libPusher#152]
My app crashes with this assertion failure, similar to this closed issue: https://github.com/lukeredpath/libPusher/issues/46
The error occurs when I quickly tell the client to disconnect then tell it to reconnect with a different authorization url. Unfortunately the stack trace is not symbolicated, I'm not sure why. But socketrocket logs this statement twice before the crash, whereas it otherwise logs it only once: "SocketRocket: In debug mode.  Allowing connection to any root cert"

**Comment by hamchapman** [comment]
Closing as stale
