### ISSUE TITLE
Unable to build from source.

### ISSUE THREAD

**Issue by zeroeth** [lukeredpath/libPusher#166]
I've got an iOS 7+ app that needs to use 64bit and going through the pangs of dependencies. libPusher (specifically headers + libPusher-combined.a) being one of them. I was previously using one of the prebuilt 1.4 downloads.

Here's what I ran into, both with the 1.5 tag and with current head 7e594e281f.

- Bundled cocoapods gem complains that its too old (Resolved by updating Gemfile)
- pod install fails in post_install hook with error (the file its complaining about exists when you check out, but seems to get deleted at some point)

<pre>
$ pod install
Analyzing dependencies

CocoaPods 0.36.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Using Kiwi (2.3.0)
Using OHHTTPStubs (3.0.2)
Using Reachability (3.1.1)
Using ReactiveCocoa (2.1.7)
Using SocketRocket (0.3.1-beta2)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

No such file or directory - Pods/Pods.xcconfig

/Users/kevinalford/Sites/libPusher/Podfile:20:in `read'
/Users/kevinalford/Sites/libPusher/Podfile:20:in `block (3 levels) in from_ruby'
/Users/kevinalford/Sites/libPusher/Podfile:19:in `open'
/Users/kevinalford/Sites/libPusher/Podfile:19:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:164:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:164:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:553:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:541:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:540:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:128:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:123:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:92:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
</pre>

I tried skipping that hook but the result is a workspace that fails to compile due to missing SRWebSocket.h reference in the libPusher code.

I can successfully build the sample libPusher app using cocoapods however. So its possible to include libPusher into my app via cocoapods, I was just trying to avoid another set of frameworks just for one external library.

Any suggestions or successful 64bit builds out there? Thanks!

**Comment by lukeredpath** [comment]
@zeroeth you shouldn't need to run bundle install or do anything with CocoaPods to compile the app as the Pods directory is checked in.

I haven't yet looked at 64 bit support but I'll see if I can have a look at this tonight.

**Comment by lukeredpath** [comment]
OK, I'm not seeing any warnings or errors so no reason why a version built from the latest HEAD shouldn't work with a 64 bit app.

Have you tried running script/build.sh? Works perfectly here and will give you a combined library in dist/libPusher.

**Comment by lukeredpath** [comment]
Here's a pre-release version of 1.6 with 64 bit support.

Please re-open this if you have problems compiling yourself using the script/build.sh script.

**Comment by zeroeth** [comment]
Thanks! The 1.6-pre builds like a charm!

I did a little research into why 1.5 was failing to build on my machine. With a fresh pull from github, 1.5's `bundle exec rake release:combined` was failing with this in the xcodebuild.log

<pre>
$ cat xcodebuild.log
Build settings from command line:
    ARCHS = armv7\ armv7s
    SDKROOT = iphoneos8.1

=== CLEAN TARGET libPusher OF PROJECT libPusher WITH CONFIGURATION Release ===

Check dependencies
[BEROR]No architectures to compile for (ARCHS=armv7\ armv7s, VALID_ARCHS=arm64 armv7 armv7s).
</pre>

I removed the .arch line here https://github.com/lukeredpath/libPusher/blob/v1.5/Rakefile#L142 and then it builds but rake fails because `build.target_build_directory` is nil in

<pre>
Your Gemfile lists the gem rest-client (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
=> Running xcodebuild clean

Cleaning target: libPusher (in libPusher.xcproject)
===================================================

Configuration: Release
....................

Finished in 0.114591 seconds.
Clean succeeded.

=> Running xcodebuild build

Building target: libPusher (in libPusher.xcproject)
===================================================

Configuration: Release
...............................................................................................................

Finished in 0.929844 seconds.
Build succeeded.

.
rake aborted!
can't convert nil into String
/Users/kevinalford/Sites/libPusher/Rakefile:87:in `join'
/Users/kevinalford/Sites/libPusher/Rakefile:87:in `copy_artefacts_from_build'
/Users/kevinalford/Sites/libPusher/Rakefile:144:in `block (3 levels) in <top (required)>'
Tasks: TOP => release:combined => release:device:cleanbuild => release:device:build
(See full trace by running task with --trace)
</pre>

**Comment by zeroeth** [comment]
For anyone trying to build 1.5, running `bundle update xcodebuild-rb` and removing `t.arch = "'armv7 armv7s'"` Worked for me.

<pre>
diff --git a/Gemfile.lock b/Gemfile.lock
index b2fe580..01e3082 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -20,7 +20,7 @@ GIT

 GIT
   remote: git://github.com/lukeredpath/xcodebuild-rb.git
-  revision: 689feb53dc4f7f0132b70b33436dc13495e9fd4c
+  revision: 3d3019756f49e892cf8166f14c9f2d5e33adf068
   specs:
     xcodebuild-rb (0.2.0)
       state_machine (~> 1.1.2)
diff --git a/Rakefile b/Rakefile
index cbed89e..b2e080d 100644
--- a/Rakefile
+++ b/Rakefile
@@ -139,7 +139,6 @@ namespace :release do
     t.configuration = "Release"
     t.sdk = "iphoneos"
     t.formatter = XcodeBuild::Formatters::ProgressFormatter.new
-    t.arch = "'armv7 armv7s'"
     t.after_build { |build| copy_artefacts_from_build(build, :include_headers => true) }
     t.xcodebuild_log_path = XCODEBUILD_LOG
   end
</pre>
