### ISSUE TITLE
PTChannel.bindToEventNamed not visible by default in Swift

### ISSUE THREAD

**Issue by jsuder** [lukeredpath/libPusher#168]
Hi,

I'm trying to set up Pusher in an iOS app written in Swift, and I've noticed that the method `bindToEventNamed:handleWithBlock:` is not visible in `PTPrivateChannel`. I've managed to solve it by additionally importing `PTPusherEventDispatcher.h` apart from `<Pusher/Pusher.h>`.

Is this a Swift bug or something that should be done differently in libPusher? I think the issue is that it doesn't see those methods because they return `PTPusherEventBinding`, and that class is only included there via `@class`.

**Comment by lukeredpath** [comment]
Interesting, I think your suspicion might be correct.

`PTPusherEventDispatcher` is not part of the public API so I should probably break out the `PTPusherEventBinding` class into a separate header if I want to make it public.

I could change the binding methods to return `id` instead (similar to how `NSNotificationCenter` does) as the binding objects are mostly opaque however they do have two methods, `eventName` and `isValid`; I need to decide if these methods are useful enough to make them public.

**Comment by jsuder** [comment]
Fixed in 1.6, thanks.
