### ISSUE TITLE
no reconnectAutomatically method - outdated docs?

### ISSUE THREAD

**Issue by jsuder** [lukeredpath/libPusher#169]
On https://pusher.com/docs/client_api_guide/client_connect it says that `PTPusher` is supposed to have a `reconnectAutomatically` method, but it looks like it doesn't have one. Was it removed?

**Comment by lukeredpath** [comment]
@jsuder yes, it was. Sorry, I've updated the README to point to the CocoaDocs documentation which is more up-to-date:

http://cocoadocs.org/docsets/libPusher/1.5/

You should handle reconnects in exceptional circumstances (e.g. no connectivity, client mis-configuration) yourself but in most cases where reconnection is possible, libPusher should handle it for you now.

**Comment by jsuder** [comment]
You should update the docs on the site too - I only came here to this repo
to report the issue, I didn't even look at the readme before, so I suppose
most people won't.

**Comment by lukeredpath** [comment]
@jsuder which site, do you mean the Pusher.com website?

**Comment by jsuder** [comment]
Yeah, I just went through everything at
https://pusher.com/docs/ios_quick_start and
https://pusher.com/docs/client_api_guide, then installed the pod and
started coding.

**Comment by leggetter** [comment]
:+1: I'll get these updated.

**Comment by lukeredpath** [comment]
@leggetter you beat me to it, I was just about to you message you! Thanks.

**Comment by lukeredpath** [comment]
@jsuder just to make it clear, if `PTPusher` disconnects, the delegate will receive a call to `pusher:connection:didDisconnectWithError:willAttemptReconnect`. The last `BOOL` parameter will indicate if the client will attempt to handle the disconnection automatically. If `YES` you don't have to do anything.

http://cocoadocs.org/docsets/libPusher/1.5/Protocols/PTPusherDelegate.html#//api/name/pusher:connection:didDisconnectWithError:willAttemptReconnect:

If the connection fails (i.e. never connects) `PTPusher` will never handle automatic reconnection.

In any case, if you want to prevent automatic reconnection handling entirely and do it all manually, you can. The following delegate method will be called before any automatic reconnect:

http://cocoadocs.org/docsets/libPusher/1.5/Protocols/PTPusherDelegate.html#//api/name/pusher:connectionWillAutomaticallyReconnect:afterDelay:

If you return `NO` from this method, the automatic reconnect will be prevented. You might want to use this, e.g. if your app has some kind of offline mode and you never want it to reconnect. HTH.

**Comment by leggetter** [comment]
@hamchapman is looking into updating the docs and will post here when that's done.

@lukeredpath - thanks very much for all the info.

**Comment by jsuder** [comment]
Hi,

another thing to fix in the docs on pusher.com - it would be nice to mention that you need to call `connect` on the `PTPusher` instance apart from just creating it... ಠ_ಠ

**Comment by hamchapman** [comment]
The docs have been updated at both https://pusher.com/docs/client_api_guide/client_connect and https://pusher.com/docs/ios_quick_start to reflect the current API of libPusher. 

Thanks for pointing out the discrepancies @jsuder and for the information @lukeredpath!

**Comment by jsuder** [comment]
:+1:

**Comment by lukeredpath** [comment]
Thanks @hamchapman
