### ISSUE TITLE
willAuthorizeChannelWithRequest: warning shows up even if you don't have that method

### ISSUE THREAD

**Issue by jsuder** [lukeredpath/libPusher#170]
It looks like the NSLog is in a wrong place - it should only be printed after the `respondsToSelector:` check, not before it.

**Comment by lukeredpath** [comment]
@jsuder this was fixed here:
https://github.com/lukeredpath/libPusher/commit/fa58b6ab99d2bc365131510cc53eefcefffdb96d

Are you using the latest 1.6alpha build or HEAD (if you're using CocoaPods)?

**Comment by jsuder** [comment]
I was using the stable version, on the version from HEAD it doesn't appear.
