### ISSUE TITLE
Presence channel isPrivate returns true

### ISSUE THREAD

**Issue by psy2k** [lukeredpath/libPusher#172]
When subscribing to a presence channel the ```func pusher(pusher: PTPusher!, didSubscribeToChannel channel: PTPusherChannel!)``` returns ```channel.isPrivate == true```. I was able to solve this by checking the isPresence property but this is an issue.

**Comment by leggetter** [comment]
Presence channels are private channels with additional functionality.

Why did you think this was a problem? Did it cause any functional problems for you?

**Comment by psy2k** [comment]
@leggetter Thanks for your reply. I was trying to trigger specific actions on the private channel. Using isPresence property to check if this channel is the presence channel or the private channel solved this for me.

**Comment by lukeredpath** [comment]
As @leggetter says, presence channels are a type of private channel so checking the isPresence property to distinguish between presence and non-presence private channels is the correct thing to do here.
