### ISSUE TITLE
Pusher Sample Code doesn't work!!

### ISSUE THREAD

**Issue by Bill-SnowWolf** [lukeredpath/libPusher#173]
I'm using libPusher 1.6. I can't even connect to pusher server. Is the libPusher still alive or nobody updates it anymore?

    PTPusher *client = [PTPusher pusherWithKey:@"app-key" delegate:self encrypted:NO]; // I assume this is "key" not "secret" there.
    [client connect];

    PTPusherChannel *channel = [client subscribeToChannelNamed:@"test"];
    NSLog(@"Channel: %@, %d", channel, channel.isSubscribed);

First of all, the delegate methods said that the "client is connecting", but didn't say "client did connected". Then the channel should subscribed automatically as document said, but it didn't.

**Comment by lukeredpath** [comment]
@Bill-SnowWolf this project is still alive; its latest release was only a few weeks ago!

I see you've closed this, did you resolve the problem? The code above is just an example; you need a strong reference to your client object or it will just be deallocated.
