### ISSUE TITLE
File not found when using use_frameworks! in cocoapods

### ISSUE THREAD

**Issue by paketinez86** [lukeredpath/libPusher#179]
I created a dynamic framework in my app to share some code, and one of the files added to the framework is linked to the Pusher SDK. The compiler recognizes the header *#import < Pusher/Pusher.h >*, but it fails at runtime showing "File not found". I installed libPusher ~> 1.6 using *link_with* and *use_frameworks!* in an iOS 8 target. Any ideas what this might be? Thanks!

**Comment by lukeredpath** [comment]
@paketinez86 I'm afraid I've not really had a chance to use CocoaPods and the new dynamic frameworks feature in iOS8. It might be worth opening an issue on the CocoaPods issue tracker and seeing what they say.

**Comment by bartg** [comment]
It works just fine if you do 

    import Pusher

Cheers! Thanks for awesome library Luke :)

**Comment by paketinez86** [comment]
It works fine. I think it was a problem with my code settings. Thanks for your response!
