### ISSUE TITLE
Channel Event History

### ISSUE THREAD

**Issue by jeffoleary1987** [lukeredpath/libPusher#180]
Is there an ability to retrieve previous events from Pusher using libPusher?

I've looked through the docs and the source code and haven't found anything yet.

Thanks!

**Comment by lukeredpath** [comment]
@jeffoleary1987 hi Jeff, no, this isn't really possible. Pusher events will only ever be received by clients that are listening at the time.

If you want to guarantee delivery, you need to use something more suitable like the Apple push notification service or some kind of persistent event stream - I've done something like this before on a project, events are stored in a queue (you could potentially have per user event streams) and the client keeps track of the ID of the last event it saw, then streams from that position when it reconnects.

I'm going to close this as its not really a libPusher issue but hope this helps.

**Comment by jeffoleary1987** [comment]
Thank you very much for your response!  

I'll try storing the events server side and see if I can build a history that way.  Thanks again!

**Comment by leggetter** [comment]
@lukeredpath @jeffoleary1987 we are hopefully soon to be releasing an Event Buffer feature that will keep a 5 minute/10k max buffer of messages per application. The idea is to handle short-lived connection interruption. This feature will require a change to libPusher to utilise it.

The next phase for us is a private external alpha of this feature.

@lukeredpath - how do you want to keep track of this? Should I drop you a note via email?

@jeffoleary1987 - would you be interested in being involved in the alpha testing phase?

**Comment by jeffoleary1987** [comment]
That sounds like it would really help with our use case.  @leggetter I would definitely be interested in being involved in the alpha phase.  Feel free to email me: joleary1987@gmail.com

**Comment by lukeredpath** [comment]
@leggetter please drop me an email but also happy to developer and discuss this openly on here as a separate issue.
